controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    diff_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - arm_shoulder_1_tilt_joint
      - arm_shoulder_2_tilt_joint
      - arm_elbow_upper_1_tilt_joint
      - arm_elbow_upper_2_tilt_joint
      - arm_elbow_lower_tilt_joint
      - arm_elbow_lower_pan_joint
      - arm_wrist_tilt_joint
      - hand_joint
      - head_pan_joint
      - head_tilt_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_shoulder_1_tilt_joint
      - arm_shoulder_2_tilt_joint
      - arm_elbow_upper_1_tilt_joint
      - arm_elbow_upper_2_tilt_joint
      - arm_elbow_lower_tilt_joint
      - arm_elbow_lower_pan_joint
      - arm_wrist_tilt_joint
      - hand_joint
      - head_pan_joint
      - head_tilt_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity