hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_pan_joint
    - head_tilt_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true
  