/**:
  ros__parameters:
    poses:
      - initial_pose
      - grasping_pose
      - detecting_pose
      - pass_high_pose
      - pass_low_pose
      - bring_bag_pose
      - trash_pose
      - put_on_shelf_pose
      - hold_shelf_handle_pose
      - into_shelf_pose
      - navigation_pose

    initial_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : 0.00
      arm_wrist_tilt_joint          : -1.57
      hand_joint                    : 0.1
      head_pan_joint                : 0.00
      head_tilt_joint               : 0.00
    
    grasping_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : 0.00
      arm_wrist_tilt_joint          : -1.57
      hand_joint                    : -0.1
      head_pan_joint                : 0.00
      head_tilt_joint               : 0.00
    
    putting_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : -1.57
      arm_wrist_tilt_joint          : -1.57
      hand_joint                    : -0.1
      head_pan_joint                : 0.00
      head_tilt_joint               : -0.70




    detecting_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : -1.57
      arm_wrist_tilt_joint          : -1.57
      hand_joint                    : 0.00
      head_pan_joint                : 0.00
      head_tilt_joint               : -0.70

    pass_high_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 0.68
      arm_elbow_lower_tilt_joint    : -1.18
      arm_elbow_lower_pan_joint     : 0.00
      arm_wrist_tilt_joint          : -0.97
      hand_joint                    : 0.00
      head_pan_joint                : 0.00
      head_tilt_joint               : 0.00

    pass_low_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : -1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : 0.00
      arm_wrist_tilt_joint          : 1.57
      hand_joint                    : 0.00
      head_pan_joint                : 0.00
      head_tilt_joint               : 0.00
    
    bring_bag_pose:
      arm_shoulder_1_tilt_joint     : 0.6
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : 0.00
      arm_wrist_tilt_joint          : -0.6
      hand_joint                    : -0.8
      head_pan_joint                : 0.00
      head_tilt_joint               : 0.00

    trash_pose:
      arm_shoulder_1_tilt_joint: 0.00
      arm_elbow_upper_1_tilt_joint: -1.57
      arm_elbow_lower_tilt_joint: 1.57
      arm_elbow_lower_pan_joint: 0.00
      arm_wrist_tilt_joint: -0.08
      hand_joint: 0.00
      head_pan_joint  : 0.00
      head_tilt_joint : -0.70

    put_on_shelf_pose:
      arm_shoulder_1_tilt_joint: 1.57
      arm_elbow_upper_1_tilt_joint: 1.57
      arm_elbow_lower_tilt_joint: -1.57
      arm_elbow_lower_pan_joint: 0.00
      arm_wrist_tilt_joint: -1.57
      hand_joint: 0.00
      head_pan_joint  : 0.00
      head_tilt_joint : -0.05

    hold_shelf_handle_pose:
      arm_shoulder_1_tilt_joint: 1.57
      arm_elbow_upper_1_tilt_joint: 1.57
      arm_elbow_lower_tilt_joint: -1.57
      arm_elbow_lower_pan_joint: 0.00
      arm_wrist_tilt_joint: -1.57
      hand_joint: 0.00
      head_pan_joint  : 0.00
      head_tilt_joint : 0.00

    into_shelf_pose:
      arm_shoulder_1_tilt_joint: 1.57
      arm_elbow_upper_1_tilt_joint: 1.57
      arm_elbow_lower_tilt_joint: -1.57
      arm_elbow_lower_pan_joint: 0.00
      arm_wrist_tilt_joint: -1.57
      hand_joint: 0.00
      head_pan_joint  : 0.00
      head_tilt_joint : 0.00

    navigation_pose:
      arm_shoulder_1_tilt_joint     : 1.57
      arm_elbow_upper_1_tilt_joint  : 1.57
      arm_elbow_lower_tilt_joint    : -1.57
      arm_elbow_lower_pan_joint     : -1.57
      arm_wrist_tilt_joint          : -1.57
      hand_joint                    : -0.20
      head_pan_joint  : 0.00
      head_tilt_joint : -0.6